TEAMS = {
    "ATL": {
        "city": "Atlanta",
        "name": "Hawks",
        "conference": "Eastern",
        "division": "Southeast",
    },
    "BKN": {
        "city": "Brooklyn",
        "name": "Nets",
        "conference": "Eastern",
        "division": "",
    },
    "BOS": {
        "city": "Boston",
        "name": "Celtics",
        "conference": "Eastern",
        "division": "Atlantic",
    },
    "CHA": {
        "city": "Charlotte",
        "name": "Hornets",
        "conference": "Eastern",
        "division": "",
    },
    "CHI": {
        "city": "Chicago",
        "name": "Bulls",
        "conference": "Eastern",
        "division": "Midwest",
    },
    "CLE": {
        "city": "Cleveland",
        "name": "Cavaliers",
        "conference": "Eastern",
        "division": "Midwest",
    },
    "DAL": {
        "city": "Dallas",
        "name": "Mavericks",
        "conference": "Western",
        "division": "",
    },
    "DEN": {
        "city": "Denver",
        "name": "Nuggets",
        "conference": "Western",
        "division": "",
    },
    "DET": {
        "city": "Detroit",
        "name": "Pistons",
        "conference": "Eastern",
        "division": "",
    },
    "GSW": {
        "city": "San Francisco",
        "name": "Warriors",
        "conference": "Western",
        "division": "",
    },
    "HOU": {
        "city": "Houston",
        "name": "Rockets",
        "conference": "Western",
        "division": "",
    },
    "IND": {
        "city": "Indianapolis",
        "name": "Pacers",
        "conference": "Eastern",
        "division": "",
    },
    "LAC": {
        "city": "Los Angeles",
        "name": "Clippers",
        "conference": "Western",
        "division": "",
    },
    "LAL": {
        "city": "Los Angeles",
        "name": "Lakers",
        "conference": "Western",
        "divisions": "",
    },
    "MEM": {
        "city": "Memphis",
        "name": "Grizzlies",
        "conference": "Western",
        "divisions": "",
    },
    "MIA": {
        "city": "Miami",
        "name": "Heat",
        "conference": "Eastern",
        "division": "",
    },
    "MIL": {
        "city": "Millwuakee",
        "name": "Bucks",
        "conference": "Eastern",
        "division": "",
    },
    "MIN": {
        "city": "Minneapolis",
        "name": "Timberwolves",
        "conference": "Western",
        "division": "",
    },
    "NOP": {
        "city": "New Orleans",
        "name": "Pelicans",
        "conference": "Western",
        "division": "",
    },
    "NYK": {
        "city": "New York",
        "name": "Knicks",
        "conference": "Eastern",
        "division": "",
    },
    "OKC": {
        "city": "Oklahoma City",
        "name": "Thunder",
        "conference": "Western",
        "division": "",
    },
    "ORL": {
        "city": "Orlando",
        "name": "Magic",
        "conference": "Eastern",
        "division": "",
    },
    "PHI": {
        "city": "Philadelphia",
        "name": "76ers",
        "conference": "Eastern",
        "division": "",
    },
    "PHX": {
        "city": "Phoenix",
        "name": "Suns",
        "conference": "Western",
        "division": "",
    },
    "POR": {
        "city": "Portland",
        "name": "Trailblazers",
        "conference": "Western",
        "division": "",
    },
    "SAC": {
        "city": "Sacramento",
        "name": "Kings",
        "conference": "Western",
        "division": "",
    },
    "SAS": {
        "city": "San Antonio",
        "name": "Spurs",
        "conference": "Western",
        "division": "",
    },
    "TOR": {
        "city": "Toronto",
        "name": "Raptors",
        "conference": "Eastern",
        "division": "",
    },
    "UTA": {
        "city": "Salt Lake City",
        "name": "Jazz",
        "conference": "Western",
        "division": "",
    },
    "WAS": {
        "city": "Washington",
        "name": "Wizards",
        "conference": "Eastern",
        "division": "",
    },
}
